[workspace]
resolver = "2"
members = ["oy-ai", "oy-agent", "oy-code-cli", "oy-tui"]

[workspace.package]
version = "0.5.1"
edition = "2024"
license = "MIT"
repository = "https://github.com/cherish-ltt/oy"

[workspace.dependencies]
# Internal crates (path deps)
oy-ai = { path = "oy-ai", version = "0.5.1" }
oy-agent = { path = "oy-agent", version = "0.5.1" }
oy-tui = { path = "oy-tui", version = "0.5.1" }

# Common third-party dependencies
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
dirs = "6"
futures = "0.3"
anyhow = "1"
color-eyre = "0.6.3"
toml = "=1.1.2"
uuid = { version = "1.23.2", features = ["v7"] }
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
chrono = "0.4.44"
tiktoken-rs = "0.12.0"
async-openai = { version = "=0.40.3", features = ["byot", "chat-completion"] }
clap = { version = "4", features = ["derive"] }
crossterm = { version = "0.29.0", features = ["event-stream", "bracketed-paste"] }
ratatui = "0.30.0"
unicode-width = "0.2.2"
pulldown-cmark = "0.13"
tempfile = "3"

# Read the optimization guideline for more details: https://ratatui.rs/recipes/apps/release-your-app/#optimizations
[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
